### DISCUSSION TITLE
[question] How can I override Kyverno policies for Signadot sidecar

### DISCUSSION THREAD

**Discussion by arjun-sd** [signadot/community#35] [Q&A] [answered]
The sidecar needs this permission which is prohibited by default: 
 
```
 securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
```
