### DISCUSSION TITLE
How can I debug the local workload connection?

### DISCUSSION THREAD

**Discussion by xolott** [signadot/community#65] [Q&A]
I have an app running on port 3000. Doing `http://localhost:3000` on my browser works as expected.

Then I run these commands:

```
signadot local connect --cluster=my-cluster 

signadot sandbox apply -f ./sandbox.yaml --set user=xolott --set branch=feature-branch --set deployment=app --set namespace=app --set port=8080 --set localPort=3000
```

Where `sandbox.yaml` contains:

```
name: "@{user}-@{branch}-sandbox"
spec:
  cluster: "my-cluster"
  ttl:
    duration: 1d
  description: "@{user} local sandbox"
  labels:
    feature: "@{branch}"
  local:
    - name: "local-@{user}-@{deployment}"
      from:
        kind: Deployment
        namespace: "@{namespace}"
        name: "@{deployment}"
      mappings:
        - port: "@{port}"
          toLocal: "localhost:@{localPort}"
```

It fails with:

```
Waiting (up to --wait-timeout=3m0s) for sandbox to be ready...
✗ Sandbox status: Not Ready: connection is not ready

Dashboard page: https://app.signadot.com/sandbox/id/z0sbzckn4qk3n


The sandbox was applied, but it may not be ready yet. To check status, run:

  signadot sandbox get xolott-main-sandbox

Error: timed out after 3m0s
```

Is there a way to debug the connection? 
Creating a sandbox in the cluster work as expected with our initial tests
