### ISSUE TITLE
[question] How can I override Kyverno policies for Signadot sidecar

### ISSUE THREAD

**Issue by arjun-sd** [signadot/community#34]
The sidecar needs this permission which is prohibited by default: 
 
```
 securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
```
