### ISSUE TITLE
[bug] Resource Plugin Stuck in Pending State

### ISSUE THREAD

**Issue by JarrodJ83** [signadot/community#78]
**Describe the bug**
If you create a resource plugin without specifying a definition, when it is used for a sandbox it will not start successfully. Instead it will be left indefinitely in a "pending" state and no logs will be available to troubleshoot.

**To Reproduce**
Create a resource plugin definition w/o setting the Namespace property.

**Expected behavior**
Resource Plugin should successfully start in the default Namespace.

**Observed behavior**
Resource plugin  left indefinitely in a "pending" state and no logs available to troubleshoot.

![Image](https://github.com/user-attachments/assets/bfaf9dbc-d7fd-4e96-a029-5683f35f1390)

```
name: test
spec:
  description: 
  runner:
    image: mcr.microsoft.com/azure-cli
    # namespace: signadot <-- omit this
  create:
  - name: create-queue
    script: |
      #!/bin/bash

      # Fail on any error
      set -e

      echo hello
```
